services:
  - type: web
    name: gp-katalog-bot
    env: node
    buildCommand: npm run install-all && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: MOYSKLAD_API_TOKEN
        sync: false
      - key: MOYSKLAD_ACCOUNT_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true 